twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      navigation:
        topic   : cmd_vel_navigation
        timeout : 0.5
        priority: 10
      joystick:
        topic   : cmd_vel_joystick
        timeout : 0.5
        priority: 80
      ps4_controller:
        topic   : cmd_vel_ps4_controller
        timeout : 0.5
        priority: 100